##################################
######
###### Project: rGSES
###### 
###### Title: Compare PGS generated by PRSice vs that of PRS-CS
###### 
###### Author: Jeremy Vollen
######
###### Description: Compare PRS-CS to PRSice results (LDpred2 to be added later)
###### for each inputted phenotype, comparing graphically as well as in terms of R2
###### 
##################################

# Clear memory
rm(list = ls())
gc()

library(tidyverse)
library(magrittr)
library(haven)
source("/Volumes/g_econ_department$/econ/biroli/geighei/code/rGSES_code/00_rGSES_functions.R")

# Directories
DATASET <- 'HRS'
PHENO <- list(list(name = 'bmi', label = 'BMI'),
              list(name = 'maxCPD', label = 'Cigs per day'),
              list(name = 'smokeInit', label = 'Smoking initiation'))
PGS_DIR <- str_c('/Volumes/g_econ_department$/econ/biroli/geighei/data/', 
                 DATASET, '/PGS/')
setwd('/Volumes/g_econ_department$/econ/biroli/geighei/code/PGS_construct/Compare_PGS/')

## --------------- Function ----------------
incr.r.edited <- function(data,  pheno_names, traits, data2, control , data_name ) {
  # Age must be called ageYears
  newData <- subset.data.frame( data2)#, select = c(control, "SESfactorHigh"))
  newData <- newData[!(is.na(newData$SESfactorHigh)),] # Keep only those with SESfactorHigh info
  newData <- newData[!(is.na(newData$SESfactorHigh)),] # Keep only those with SESfactorHigh info
  newData$male  <- as.numeric(newData$male)
  newData$male[newData$male==2] <- 0
  newData$male[newData$male==1] <- 1
  
  newData <- cbind(data , newData)
  newData$ageYears2 <- sqrt(newData$ageYears)
  newData$ageMale <- newData$ageYears * newData$male 

  # Matrix for incremental R2
  lm_matrix = matrix(nrow=length(traits), ncol=3)
  dimnames(lm_matrix) = list( traits,
                              c("OLS", "OLS1", "OLS8"))
  # Extract traits and pgs
  traits_var <- pheno_names[seq(3, length(pheno_names), 3)]
  pgs_1 <- pheno_names[seq(2, length(pheno_names), 3)]
  pgs_8 <- pheno_names[seq(1, length(pheno_names), 3)]
  # perform lm, store adj. R2 and populate the matrix
  for(i in 1:length(traits_var)){
    control <- c("ageYears2" , "ageMale", control)
    x <- paste(traits_var[i], " ~ "  ,paste(control, collapse=" + "), sep = "")
    lm_trait <- lm(  x , data = newData)
    
    if (pgs_1[i]=="missing" #| pgs_8[i]=="missing"
        ) {
      lm_matrix[i, ] <- c( summary(lm_trait)$r.squared , "NA" , "NA" )
    }
    else {
      control1 <- c( pgs_1[i] , control)
      x <- paste(traits_var[i], " ~ "  ,paste(control1, collapse=" + "), sep = "")
      lm_pgs1 <- lm(  x , data = newData)
      control2 <- c( pgs_8[i] , control)
      x <- paste(traits_var[i], " ~ "  ,paste(control2, collapse=" + "), sep = "")
      lm_pgs8 <- lm(  x , data = newData)
      lm_matrix[i, ] <- c( summary(lm_trait)$r.squared, summary(lm_pgs1)$r.squared , summary(lm_pgs8)$r.squared )
    }
    if(pgs_8[i]=="missing"){
      lm_matrix[i,3] <- "NA"
    }
  }
  lm_table <- as.data.frame(lm_matrix, stringsAsFactors = FALSE) 
  colnames(lm_table)  <-  c("r.ols", "r.ols1", "r.ols8")
  lm_table$increment1 <- 0
  lm_table$increment8 <- 0
  lm_table$r.ols8 <- as.numeric(lm_table$r.ols8)
  lm_table$r.ols1 <- as.numeric(lm_table$r.ols1)
  lm_table$r.ols <- as.numeric(lm_table$r.ols)
  lm_table$increment1 <- as.numeric(lm_table$increment1)
  lm_table$increment8 <- as.numeric(lm_table$increment8)
  # Calculate incremental R2
  
  for(i in 1:length(traits_var)){
      lm_table$increment1 <-   (lm_table$r.ols1 - lm_table$r.ols) * 100
      lm_table$increment8 <-   (lm_table$r.ols8 - lm_table$r.ols) * 100
  }
  lm_table$increment1 <- as.numeric(lm_table$increment1)
  lm_table$increment8 <- as.numeric(lm_table$increment8)
  lm_table <- format(lm_table, scientific = FALSE, digits = 2)
  
  # Output
  pdf(paste("output/incrementalR2", data_name, ".pdf",sep=""), 20,15)
  
  colnames(lm_table)  <- c("R squared OLS", "R squared OLS PGS1", "R squared OLS PGS5e8", "Incremental R2 PGS1  (%)", "Incremental R2 PGS5e8 (%)")
  table <- tableGrob(lm_table)
  
  title <- textGrob("Incremental R squared for PGS-1 ans PGS-5e8" ,just="center", gp = gpar(fontsize = 20))
  footnote <- textGrob(paste("data: ", data_name, sep= ""),x=0, hjust=0,
                       gp=gpar( fontface="italic"))
  
  padding <- unit(0.3,"line")
  table <- gtable_add_rows(table, 
                           heights = grobHeight(title) + padding,
                           pos = 0)
  table <- gtable_add_rows(table, 
                           heights = grobHeight(footnote)+ padding)
  table <- gtable_add_grob(table, list(title, footnote),
                           t=c(1, nrow(table)), l=c(1,2), 
                           r=ncol(table))
  
  grid.newpage()
  grid.draw(table)
  invisible(dev.off())
  
  # SAVE TABLE
  kable(lm_table, "html",
        col.names = c("R squared OLS", "R squared OLS PGS1", "R squared OLS PGS5e8", 
                      "Incremental R2 PGS1  (%)", "Incremental R2 PGS5e8  (%)")) %>%
    kable_styling(c("striped", "bordered")) %>% 
    add_header_above(c(" ", "R squared" = 3 , "Incremental R squared" = 2)) %>%
    footnote(general = data_name,
             general_title = "Source: ",
             footnote_as_chunk = T) %>%
    save_kable(paste("output/incrementalR2_", data_name,".pdf",sep=""))
  
  # PRINT TABLE
  kable(lm_table,
        col.names = c("R squared OLS", "R squared OLS PGS1", "R squared OLS PGS5e8", 
                      "Incremental R2 PGS1  (%)", "Incremental R2 PGS5e8  (%)")) %>%
    kable_styling(c("striped", "bordered")) %>% 
    add_header_above(c(" ", "R squared" = 3 , "Incremental R squared" = 2)) %>%
    footnote(general = data_name,
             general_title = "Source: ",
             footnote_as_chunk = T) 
}

comparisonPlots <- function(df, name,
                            out = str_c('output/', name, '_charts.pdf')){
  # simple scatter
  p_scatter <- ggplot(data = df, aes(x=prsice, y = prscs)) + 
    geom_point(aes(alpha=0.1)) + ggtitle('PGS scatter plot comparison')
  
  # quantile-quantile plot to compare both distributions to normal
  p_qq <- ggplot(data = df %>% gather(key = Score_type, value = Score, -c(FID, IID)), 
           aes(sample=Score, color=Score_type)) + 
    geom_qq() + ggtitle('PGS qq-plot (vs. standard normal) comparison')
  
  # attempt at rank-rank plots
  percentiles <- df %>%
    mutate(percentile = ntile(prsice, n=100)) %>%
    group_by(percentile) %>%
    summarise_at(vars(starts_with('prs')), mean)
  # PRScs percentile avgs vs PRSice percentile avgs using 100 percentiles in PRSice
  p_percentiles <- ggplot(percentiles, aes(x=prsice, y=prscs)) +
    geom_point() + geom_abline(slope=1, intercept=0) +
    ggtitle('Average percentile score (percentiles using PRSice ranking)')
  p_percentiles_overlay <- 
    ggplot(percentiles %>% 
             gather(key = Score_type, value = Score, -percentile),
           aes(x = percentile, y = Score, color = Score_type)) + 
    geom_point() + ggtitle('Average percentile score (percentiles using PRSice ranking)')
  
  # now let's see what's happening beneath the surface of the above plots
  percentiles2 <- df %>%
    mutate(rank_prsice = cume_dist(prsice),
           rank_prscs = cume_dist(prscs))
  p_rankrank <- ggplot(percentiles2,
                       aes(x = rank_prsice, y = rank_prscs, alpha=0.1)) + 
    geom_point() + geom_abline(slope = 1, intercept = 0) + 
    ggtitle('Rank-rank plot PGS comparison')
  
  pdf(out, onefile = T, width = 7, height = 5)
  print(p_scatter)
  print(p_qq)
  print(p_percentiles)
  print(p_percentiles_overlay)
  print(p_rankrank)
  plot.new()
  text(.5, .5, paste("R2 of regression of prscs score against prsice score is",
                     summary(lm(df$prscs ~ df$prsice))$r.squared))
  dev.off()
}

## --------------- Read Data ----------------
# pgs
prsice <- 
  map(PHENO, 
      ~ read_table2(str_c(PGS_DIR, 'PRSice/', 
                          DATASET, '_', .[["name"]], '.all.score')) %>%
        mutate(prsice = `1`)) %>% 
  set_names(map(PHENO,1))

prscs <- 
  map(PHENO,
      ~ read_table2(str_c(PGS_DIR, 'PRScs/', 
                          .[["name"]], '/', .[["name"]], '_PGS.profile')) %>%
        mutate(prscs = SCORE)) %>%
  set_names(map(PHENO,1))

# data necessary for incremental R2 calculation
hrs_new <- read_dta("/Volumes/g_econ_department$/econ/biroli/geighei/data/HRS/phenoclean/HRS_GxSES_analysis.dta") %>%
  # shouldn't be necessary after Pia cleans up names
   rename(maxCPD = cigsAll_Current,
         smokeInit = cesSmoke_GSCAN)
## --------------- Process Data ----------------
# Clean data
prsice_clean <- prsice %>%
  map(~ select(., FID, IID, contains("prsice")))
prscs_clean <- prscs %>% 
  map(~ select(., FID, IID, contains("prscs")))

# Merge data
merged <- map2(prsice_clean, prscs_clean,
               ~ inner_join(.x, .y, by = c('FID', 'IID')))

# Normalize polygenic scores to mean 0 standard dev 1
normalized <- merged %>%
  map(~ mutate_at(., vars(contains('prs')), ~ (. - mean(.)) / sd(.)))

## --------------- Comparison charts ----------------

# for each phenotype, call comparison plots which will create a pdf
walk(PHENO, ~ comparisonPlots(df=normalized[[.[["name"]]]], name=.[["name"]]))

## ------------ Incremental R2 --------------------
# create master list of scores for all phenotypes and engines
full <- 
  map2(normalized, names(normalized), 
       function(x,y)
         rename_at(x, vars(starts_with("prs")), ~ paste0(., "_", y))) %>%
  reduce(inner_join, by = c('FID', 'IID'))

# join with PGS
all_data <- hrs_new %>%
  left_join(full, by = c("iid" = "IID"))

all_data <- select(all_data,
  HHID, PN, hhipn,         # highIndex based on 0-4
  SESindexHigh,            # highIndex based on 0-4
  SESIndex,                # SESIndex based on 0-4
  SESfactor,               # new factor score (old name SESFChatB)
  SESfactorHigh,           # highIndex based on new factor score
  starts_with("prs"))

# Add high Factor
all_data$SESfactorHigh  <- as.numeric(all_data$SESfactorHigh)
all_data$SESfactorHigh[all_data$SESfactorHigh==1] <- 0
all_data$SESfactorHigh[all_data$SESfactorHigh==2] <- 1

# Add high Index
all_data$SESindexHigh  <- as.numeric(all_data$SESindexHigh)
all_data$SESindexHigh[all_data$SESindexHigh==1] <- 0
all_data$SESindexHigh[all_data$SESindexHih==2] <- 1

all_data <- all_data[!(is.na(all_data$SESfactorHigh)),] # Keep only those with SESfactorHigh info
all_data$missing <- 0

traits <- map(PHENO, ~ c(paste('PRSice', .[[2]]), paste('PRS-CS', .[[2]]))) %>%
  flatten_chr()

#     PGS 10-8,                PGS 1,           Phenotype
var_names_both <- map(PHENO, ~ c("missing", str_c('prsice_', .[[1]]), .[[1]],
                                 "missing", str_c('prscs_', .[[1]]), .[[1]])) %>%
  flatten_chr()

controls <-  c( "ageYears", "male" , "ev1" , "ev2" ,"ev3" , "ev4" , "ev5" , "ev6" , "ev7" , "ev8" , "ev9" , "ev10" )

incr.r.edited(data = all_data,  pheno_names = var_names_both , traits = traits, 
              data2 = hrs_new, control = controls, data_name = DATASET)
