##################################
######
###### Project: rGSES
###### 
###### Title: Compare PGS generated by PRSice vs that of PRS-CS
###### 
###### Author: Jeremy Vollen
######
###### Description: 
###### 
##################################

# Clear memory
rm(list = ls())
gc()

library(tidyverse)
library(magrittr)
library(haven)
source("/Volumes/g_econ_department$/econ/biroli/geighei/code/rGSES_code/00_rGSES_functions.R")

# Directories
DATASET <- 'HRS'
PHENO <- 'bmi'
PHENO_TITLE <- 'BMI'
PGS_DIR <- str_c('/Volumes/g_econ_department$/econ/biroli/geighei/data/', 
                 DATASET, '/PGS/')
setwd('/Volumes/g_econ_department$/econ/biroli/geighei/code/PGS_construct/Compare_PGS/')

## --------------- Function ----------------
incr.r <- function(data,  pheno_names, traits, data2, control , data_name ) {
  # Age must be called ageYears
  newData <- subset.data.frame( data2)#, select = c(control, "SESfactorHigh"))
  newData <- newData[!(is.na(newData$SESfactorHigh)),] # Keep only those with SESfactorHigh info
  newData <- newData[!(is.na(newData$SESfactorHigh)),] # Keep only those with SESfactorHigh info
  newData$male  <- as.numeric(newData$male)
  newData$male[newData$male==2] <- 0
  newData$male[newData$male==1] <- 1
  
  newData <- cbind(data , newData)
  newData$ageYears2 <- sqrt(newData$ageYears)
  newData$ageMale <- newData$ageYears * newData$male 
  
  # Former Smoker
  # newData$formerSmoker  <- as.numeric(newData$formerSmoker)
  # newData$formerSmoker[newData$formerSmoker==0] <- 0
  # newData$formerSmoker[newData$formerSmoker==1] <- 1
  
  
  # Matrix for incremental R2
  lm_matrix = matrix(nrow=length(traits), ncol=3)
  dimnames(lm_matrix) = list( traits,
                              c("OLS", "OLS1", "OLS8"))
  # Extract traits and pgs
  traits_var <- pheno_names[seq(3, length(pheno_names), 3)]
  pgs_1 <- pheno_names[seq(2, length(pheno_names), 3)]
  pgs_8 <- pheno_names[seq(1, length(pheno_names), 3)]
  # perform lm, store adj. R2 and populate the matrix
  for(i in 1:length(traits_var)){
    control <- c("ageYears2" , "ageMale", control)
    x <- paste(traits_var[i], " ~ "  ,paste(control, collapse=" + "), sep = "")
    lm_trait <- lm(  x , data = newData)
    
    if (pgs_1[i]=="missing" #| pgs_8[i]=="missing"
        ) {
      lm_matrix[i, ] <- c( summary(lm_trait)$r.squared , "NA" , "NA" )
    }
    else {
      control1 <- c( pgs_1[i] , control)
      x <- paste(traits_var[i], " ~ "  ,paste(control1, collapse=" + "), sep = "")
      lm_pgs1 <- lm(  x , data = newData)
      control2 <- c( pgs_8[i] , control)
      x <- paste(traits_var[i], " ~ "  ,paste(control2, collapse=" + "), sep = "")
      lm_pgs8 <- lm(  x , data = newData)
      lm_matrix[i, ] <- c( summary(lm_trait)$r.squared, summary(lm_pgs1)$r.squared , summary(lm_pgs8)$r.squared )
    }
  }
  lm_table <- as.data.frame(lm_matrix, stringsAsFactors = FALSE) 
  colnames(lm_table)  <-  c("r.ols", "r.ols1", "r.ols8")
  lm_table$increment1 <- 0
  lm_table$increment8 <- 0
  lm_table$r.ols8 <- as.numeric(lm_table$r.ols8)
  lm_table$r.ols1 <- as.numeric(lm_table$r.ols1)
  lm_table$r.ols <- as.numeric(lm_table$r.ols)
  lm_table$increment1 <- as.numeric(lm_table$increment1)
  lm_table$increment8 <- as.numeric(lm_table$increment8)
  # Calculate inclremental R2
  
  for(i in 1:length(traits_var)){
    if (is.na(lm_table$r.ols1[i]) == TRUE | is.na(lm_table$r.ols8[i]) == TRUE) {
      lm_table$increment1[i] <- "NA" 
      lm_table$increment8[i] <- "NA" 
    }
    else {
      lm_table$increment1 <-   (lm_table$r.ols1 - lm_table$r.ols) * 100
      lm_table$increment8 <-   (lm_table$r.ols8 - lm_table$r.ols) * 100
    }
  }
  lm_table$increment1 <- as.numeric(lm_table$increment1)
  lm_table$increment8 <- as.numeric(lm_table$increment8)
  lm_table <- format(lm_table, scientific = FALSE, digits = 2)
  
  # Output
  pdf(paste("incrementalR2", data_name, ".pdf",sep=""), 20,15)
  
  colnames(lm_table)  <- c("R squared OLS", "R squared OLS PGS1", "R squared OLS PGS5e8", "Incremental R2 PGS1  (%)", "Incremental R2 PGS5e8 (%)")
  table <- tableGrob(lm_table)
  
  title <- textGrob("Incremental R squared for PGS-1 ans PGS-5e8" ,just="center", gp = gpar(fontsize = 20))
  footnote <- textGrob(paste("data: ", data_name, sep= ""),x=0, hjust=0,
                       gp=gpar( fontface="italic"))
  
  padding <- unit(0.3,"line")
  table <- gtable_add_rows(table, 
                           heights = grobHeight(title) + padding,
                           pos = 0)
  table <- gtable_add_rows(table, 
                           heights = grobHeight(footnote)+ padding)
  table <- gtable_add_grob(table, list(title, footnote),
                           t=c(1, nrow(table)), l=c(1,2), 
                           r=ncol(table))
  
  grid.newpage()
  grid.draw(table)
  invisible(dev.off())
  
  
  # SAVE TABLE
  kable(lm_table, "html",
        col.names = c("R squared OLS", "R squared OLS PGS1", "R squared OLS PGS5e8", 
                      "Incremental R2 PGS1  (%)", "Incremental R2 PGS5e8  (%)")) %>%
    kable_styling(c("striped", "bordered")) %>% 
    add_header_above(c(" ", "R squared" = 3 , "Incremental R squared" = 2)) %>%
    footnote(general = data_name,
             general_title = "Source: ",
             footnote_as_chunk = T) %>%
    save_kable(paste("incrementalR2_", data_name,".pdf",sep=""))
  
  # PRINT TABLE
  kable(lm_table,
        col.names = c("R squared OLS", "R squared OLS PGS1", "R squared OLS PGS5e8", 
                      "Incremental R2 PGS1  (%)", "Incremental R2 PGS5e8  (%)")) %>%
    kable_styling(c("striped", "bordered")) %>% 
    add_header_above(c(" ", "R squared" = 3 , "Incremental R squared" = 2)) %>%
    footnote(general = data_name,
             general_title = "Source: ",
             footnote_as_chunk = T) 
  
}

## --------------- Read Data ----------------
# pgs
prsice <- read_table2(str_c(PGS_DIR, 'PRSice/', DATASET, '_', PHENO, '.all.score'))
prscs <- read_table2(str_c(PGS_DIR, 'PRScs/', PHENO, '/', PHENO, '_PGS.profile'))

# data necessary for incremental R2 calculation
hrs_new <- read_dta("/Volumes/g_econ_department$/econ/biroli/geighei/data/HRS/phenoclean/HRS_GxSES_analysis.dta")

## --------------- Process Data ----------------
# Clean data
prsice_clean <- prsice %>%
  select(FID, IID, SCORE = `1`)
prscs_clean <- prscs %>% 
  select(FID, IID, SCORE)

# Merge data
merged <- inner_join(prsice_clean, prscs_clean, 
                     by = c('FID', 'IID'), suffix = c('_prsice', '_prscs'))

# Normalize polygenic scores to mean 0 standard dev 1
normalized <- merged %>%
  mutate_at(vars(contains('SCORE')), ~ (. - mean(.)) / sd(.))

## --------------- Comparison charts ----------------
p <- ggplot(data = normalized, aes(x=SCORE_prsice, y = SCORE_prscs))

# simple scatter
p + geom_point(aes(alpha=0.1))

# quantile-quantile plot to compare distributions
ggplot(data = normalized) + 
  geom_qq(aes(sample = SCORE_prsice), color = 'purple') + 
  geom_qq(aes(sample = SCORE_prscs), color = 'cyan')

## ------------ Incremental R2 --------------------
# join with PGS
all_data <- hrs_new %>%
  left_join(normalized, by = c("iid" = "IID")) %>%
  rename_at(vars(contains("SCORE")), 
            ~ .)

all_data <- subset(all_data, select = c(
  HHID, PN, hhipn,         # highIndex based on 0-4
  SESindexHigh,                                      # highIndex based on 0-4
  SESIndex,                                          # SESIndex based on 0-4
  SESfactor,                                         # new factor score (old name SESFChatB)
  SESfactorHigh,                                     # highIndex based on new factor score
  SCORE_prsice, SCORE_prscs))             # Education 

# Add high Factor
all_data$SESfactorHigh  <- as.numeric(all_data$SESfactorHigh)
all_data$SESfactorHigh[all_data$SESfactorHigh==1] <- 0
all_data$SESfactorHigh[all_data$SESfactorHigh==2] <- 1

# Add high Index
all_data$SESindexHigh  <- as.numeric(all_data$SESindexHigh)
all_data$SESindexHigh[all_data$SESindexHigh==1] <- 0
all_data$SESindexHigh[all_data$SESindexHigh==2] <- 1

all_data <- all_data[!(is.na(all_data$SESfactorHigh)),] # Keep only those with SESfactorHigh info
all_data$missing <- 0

traits <- c(paste('PRSice', PHENO_TITLE), paste('PRS-CS Smoking Cessation', PHENO_TITLE))

#     PGS 10-8,                PGS 1,           Phenotype
var_names_both   <- c(  
  "missing" ,            "SCORE_prsice" ,            PHENO ,
  "missing" ,            "SCORE_prscs"  ,            PHENO
  )

controls <-  c( "ageYears", "male" , "ev1" , "ev2" ,"ev3" , "ev4" , "ev5" , "ev6" , "ev7" , "ev8" , "ev9" , "ev10" )

incr.r(data = all_data,  pheno_names = var_names_both , traits = traits, data2 = hrs_new, 
       control = controls, data_name = DATASET)
